name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ZIP Deployment Package
        # CP env variables?...
        run: zip -r deploy.zip ./

      - name: Deploy to Elastic Beanstalk
        run: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Laravel
          environment_name: Portfolio-Github-Action
          existing_bucket_name: elasticbeanstalk-us-east-1-290427685328
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
