name: Apply Code Style Fixes

on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened, ready_for_review ]

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, sqlite3
          coverage: none

      - name: Install node dependencies
        run: npm ci

      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Code Formatting
        run: |
          echo "running prettier..."
          npm run prettier

          echo "running php-cs fixer..."
          vendor/bin/php-cs-fixer fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Code Style Fixes
